esphome:
  name: "family-room-bluetooth-proxy"
  friendly_name: "family-room-bluetooth-proxy"

esp32:
  board: seeed_xiao_esp32c6
  framework:
    type: esp-idf

# Enable IPv6
network:
    enable_ipv6: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key_family_room_bluetooth_proxy

ota:
  - platform: esphome
    password: !secret ota_password_family_room_bluetooth_proxy

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Bluetooth Proxy to Home Assistant
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true