esphome:
  name: home-office-lego-controller
  friendly_name: Home Office Lego Controller

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key_home_office_lego_controller

ota:
  - platform: esphome
    password: !secret ota_password_home_office_lego_controller

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Pico W Pinout: https://www.raspberrypi.com/documentation/microcontrollers/raspberry-pi-pico.html#pinout-and-design-files19

switch:
  - platform: gpio
    pin: GPIO22
    id: blink_mk2
    name: "Blink! LEDs"