esphome:
  name: shack-lego-controller
  friendly_name: Shack Lego Controller

esp32:
  board: seeed_xiao_esp32c6
  framework:
    type: esp-idf

# Enable IPv6
network:
    enable_ipv6: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key_shack_lego_controller

ota:
  - platform: esphome
    password: !secret ota_password_shack_lego_controller

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

switch:
  - platform: gpio
    pin: GPIO0
    id: usb_port_0
    name: "USB Port 0"
  - platform: gpio
    pin: GPIO18
    id: usb_port_10
    name: "USB Port 1"