esphome:
  name: utility-bluetooth-proxy
  friendly_name: "Utility Bluetooth Proxy"

esp32:
  board: nodemcu-32s
  #platformio_options:
  #  platform: espressif32
  #  board: az-delivery-devkit-v4
  #  board_build.mcu: esp32
  #  board_build.f_cpu: 240000000L
  framework: 
    type: esp-idf

# Enable logging
logger:

# Enable IPv6
network:
    enable_ipv6: true

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key_utility_bluetooth_proxy

ota:
  platform: esphome
  password: !secret ota_password_utility_bluetooth_proxy

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Bluetooth Proxy to Home Assistant
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true